--- #YAML:1.0
name:                Date-Components
version:             v0.0.1
abstract:            Parses, processes and formats ONLY dates and date components
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Carp:                          1.04
    Readonly:                      1.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David McAllister <dreamer@suse.de>
